<script>
    var nameHotspot = {
        'overview1' : '{{ trans('all.overview1') }}',
        'overview2' : '{{ trans('all.overview2') }}',
        'overview3' : '{{ trans('all.overview3') }}',
        'cho_bau_bang' : '{{ trans('all.cho_bau_bang') }}',
        'bx_bau_bang' : '{{ trans('all.bx_bau_bang') }}',
        'pccc' : '{{ trans('all.pccc') }}',
        'hai_quan' : '{{ trans('all.hai_quan') }}',
        'xlnt' : '{{ trans('all.xlnt') }}',
        'kolon' : '{{ trans('all.kolon') }}',
        'paihong' : '{{ trans('all.paihong') }}',
        'xlnt_mr' : '{{ trans('all.xlnt_mr') }}',
        'chot_bv' :'{{ trans('all.chot_bv') }}',
        'far_eastern' : '{{ trans('all.far_eastern') }}',
        'buu_dien' : '{{ trans('all.buu_dien') }}',
        'dien_luc_evn' : '{{ trans('all.dien_luc_evn') }}',
        'nha_o_cn' : '{{ trans('all.nha_o_cn') }}',
        'nha_o_xh' : '{{ trans('all.nha_o_xh') }}',
        'biwase' : '{{ trans('all.biwase') }}',
        'san_bong' : '{{ trans('all.san_bong') }}',
        'vntt' : '{{ trans('all.vntt') }}',
        'y_te' : '{{ trans('all.y_te') }}',
        'tram_dien' : '{{ trans('all.tram_dien') }}',
        'vh_tdtt' : '{{ trans('all.vh_tdtt') }}',
        'ca_bau_bang' : '{{ trans('all.ca_bau_bang') }}',
        'truong_hoc' : '{{ trans('all.truong_hoc') }}',
        'ngan_hang' : '{{ trans('all.ngan_hang') }}',
        'van_phong_bql' : '{{ trans('all.van_phong_bql') }}',
        'xlnt2' : '{{ trans('all.xlnt2') }}',
        'cap_3' : '{{ trans('all.cap_3') }}',
        'nha_tre' : '{{ trans('all.nha_tre') }}',
        'van_phong_bql_kcn' : '{{ trans('all.van_phong_bql_kcn') }}',
        'truong_tieu_hoc_bau_bang' : '{{ trans('all.truong_tieu_hoc_bau_bang') }}',
        'tmn_ad' : '{{ trans('all.tmn_ad') }}',
        'nha_xuong_xay_san' : '{{ trans('all.nha_xuong_xay_san') }}',
        'truong_tieu_hoc_kim_dong' : '{{ trans('all.truong_tieu_hoc_kim_dong') }}',
        'ql_13' : '{{ trans('all.ql_13') }}',
        'trung_tam_hanh_chinh' : '{{ trans('all.trung_tam_hanh_chinh') }}',
        'nm_far_easter_gd_1' : '{{ trans('all.nm_far_easter_gd_1') }}',
        'tcn' : '{{ trans('all.tcn') }}',
        'tdmr' : '{{ trans('all.tdmr') }}',
        'nha_hang_thuy_linh': '{{trans('all.nha_hang_thuy_linh')}}',
        'shop_toc' : '{{ trans('all.shop_toc') }}',
        'buu_dien_dien_luc_evn' : '{{ trans('all.buu_dien_dien_luc_evn') }}',
        'tram_bom_chuyen_cap_nuoc_thai': '{{ trans('all.tram_bom_chuyen_cap_nuoc_thai')}}',
        'truc_duong_chinh': '{{trans('all.truc_duong_chinh')}}',
        'cong_kcn_bau_bang': '{{trans('all.cong_kcn_bau_bang')}}',
    }

    var imageHotspot = {
        'cang_cat_lai': 'images\\cang_cat_lai{{(empty(Session::get('website_language')) || Session::get('website_language') == 'en') ? '_en' : ''}}.png',
        'hcm': 'images\\hcm{{(empty(Session::get('website_language')) || Session::get('website_language') == 'en') ? '_en' : ''}}.png',
        'long_thanh': 'images\\long_thanh{{(empty(Session::get('website_language')) || Session::get('website_language') == 'en') ? '_en' : ''}}.png',
        'tan_son_nhat': 'images\\tan_son_nhat{{(empty(Session::get('website_language')) || Session::get('website_language') == 'en') ? '_en' : ''}}.png',
        'intro': 'intro{{(empty(Session::get('website_language')) || Session::get('website_language') == 'en') ? '_en' : ''}}.png',
    }
</script>
